//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tellyt
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalMedia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExternalMedia()
        {
            this.Questions = new HashSet<Question>();
        }
    
        public int Id { get; set; }
        public string Bucket { get; set; }
        public string Url { get; set; }
        public string ThumbUrl { get; set; }
        public string Type { get; set; }
        public string Key { get; set; }
        public System.DateTime LastModified { get; set; }
        public string UserId { get; set; }
        public string ThumbKey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
    }
}
